Update dependencies
CleverbotIO/rust-cleverbot.io pull request #8
Opened 2017-01-26 18:10 UTC by sbxx

Made it work with current versions of the dependencies. Also applied rustfmt. Works with stable 1.14 and current nightly.

2017-01-26 18:22 UTC, elifoster commented
Can you resubmit this (or undo and just push again) without the formatting changes?

2017-01-26 18:23 UTC, elifoster requested changes
Can you resubmit this (or undo and just push again) without the formatting changes?

2017-01-26 19:48 UTC, sbxx commented
I've reverted the formatting.

2017-01-26 22:10 UTC, elifoster requested changes

2017-01-26 22:10 UTC, elifoster commented on Cargo.toml
> +version = "1.0.1"
Can you undo this version bump?

2017-01-26 22:11 UTC, elifoster commented
Looks good except for that one little change I requested. I'll test it by the weekend. Thanks for the contribution :smile:

2017-01-26 22:11 UTC, sbxx commented
There you go!

2017-01-30 20:59 UTC, elifoster approved these changes

2017-01-30 20:59 UTC, merged